export const sources = [
  { id: 'about', label: 'About Om', url: 'https://om7203.github.io/om-vaghasiya-portfolio/#about', fact: 'Om Vaghasiya is finishing a Bachelor of Science in Artificial Intelligence at Technische Hochschule Deggendorf, expected October 2026. He is looking for a full-time role in AI or software development.' },
  { id: 'story', label: 'Personal story', url: 'https://om7203.github.io/om-vaghasiya-portfolio/#personal', fact: 'Om grew up in Surat, Gujarat, India. He studied Computer Engineering in India for one year, discovered AI, and moved to Germany to study it. His elder brother helped him understand the field. He likes teamwork and learning new things. Outside work he enjoys cricket, travelling, food, films and series.' },
  { id: 'bauhaus', label: 'Experience: Bauhaus Luftfahrt', url: 'https://om7203.github.io/om-vaghasiya-portfolio/#experience', fact: 'Since March 2026 Om has worked as a working student in Propulsion System Design at Bauhaus Luftfahrt. He works on an AI assistant for MATLAB engineering tasks using LLMs, MCP tool calling, Git repositories, document context and Docker environments for controlled code execution. His ongoing bachelor thesis compares local and cloud LLMs on MATLAB coding, refactoring, analysis, visualization and tool use.' },
  { id: 'drees', label: 'Experience: Drees & Sommer', url: 'https://om7203.github.io/om-vaghasiya-portfolio/#experience', fact: 'From August 2025 through January 2026, Om interned in Artificial Intelligence at Drees & Sommer. He helped develop a framework evaluating more than 30 LLMs and worked on OCR and vision-language models for document analysis, model APIs, and data pipelines for construction-price forecasting. Employer code and evaluation data are private.' },
  { id: 'skills', label: 'Skills', url: 'https://om7203.github.io/om-vaghasiya-portfolio/#skills', fact: 'The portfolio lists LLM evaluation, prompt engineering, RAG, tool calling, Python, MATLAB, JavaScript, FastAPI, React, Docker, Git, CI/CD, SQL, PyTorch, TensorFlow, scikit-learn, OCR and computer vision. These are self-reported skills, with selected examples linked elsewhere on the site.' },
  { id: 'support', label: 'Support Agent Lab', url: 'https://om7203.github.io/om-vaghasiya-portfolio/projects/support-agent.html', fact: 'Support Agent Lab is Om’s independent learning project. It routes fictional support questions through validation, retrieval, cited answers, abstention or human handoff. The server workflow uses LangGraph and has tests, evaluation cases and a locally tested n8n integration. The public browser demo is deterministic and does not call a live LLM or a real ticket system.' },
  { id: 'support_code', label: 'Support Agent Lab code', url: 'https://github.com/Om7203/support-agent-lab', fact: 'The public Support Agent Lab repository contains its workflow code, tests, evaluation cases and architecture notes.' },
  { id: 'evidence', label: 'Evidence Desk', url: 'https://om7203.github.io/om-vaghasiya-portfolio/projects/evidence-desk.html', fact: 'Evidence Desk is Om’s independent page-cited document-search experiment over two public NIST PDFs. The browser demo ranks extracted passages with BM25; a local Python API uses TF-IDF. It shows source pages and documented misses. The public demo is extractive and does not generate answers or process private documents.' },
  { id: 'evidence_code', label: 'Evidence Desk code', url: 'https://github.com/Om7203/evidence-desk', fact: 'The public Evidence Desk repository has code, architecture notes, tests and separate evaluations for the browser demo and local API.' },
  { id: 'emotion', label: 'Emotion detection', url: 'https://om7203.github.io/om-vaghasiya-portfolio/projects/emotion-detection.html', fact: 'In a university team project, Om helped classify short text into six emotions using GloVe embeddings, a BiLSTM, stratified cross-validation, early stopping and macro-F1 evaluation. This is team work, not a solo project.' },
  { id: 'plate', label: 'License plate recognition', url: 'https://om7203.github.io/om-vaghasiya-portfolio/projects/license-plate.html', fact: 'Om’s license plate project uses a staged video pipeline with vehicle and plate detection, SORT tracking, character recognition and annotated output. The repository has example input and output video. No performance benchmark is published.' },
  { id: 'contact', label: 'Contact', url: 'https://om7203.github.io/om-vaghasiya-portfolio/#contact', fact: 'Om can be contacted by email at omvaghasiya2003@gmail.com or on LinkedIn at https://www.linkedin.com/in/om-vaghasiya-a972ba286/.' }
];
